# Welcome to Jekyll!
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings

title: /var/log/vishesh
author: Vishesh Yadav
email:
description: >-
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vishesh.github.io"
twitter_username: visheshyv
github_username:  vishesh
linkedin_username: visheshyadav

# Build settings
# theme: jekyll-whiteglass
theme: minima
#plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
